version: "{build}"
branches:
  except:
    - gh-pages
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm run build
  - Compress-Archive -Path . -DestinationPath natori-live-notifier.zip
build: off
deploy: off
environment:
  matrix:
    - nodejs_version: LTS
artifacts:
  - path: natori-live-notifier.zip
    name: natori-live-notifier.zip
